version: '3.8'

services:
  dev-database:
    image: mysql:5.7.36
    container_name: ${DB_HOST}
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - solanches-mysql-dev:/var/lib/mysql
      - ./mysql-restorage:/docker-entrypoint-initdb.d

volumes:
  solanches-mysql-dev:
